package Difficulty5Percent;

import java.math.BigInteger;

//			---Question---



//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



public class EvenFibonacci {
	static long count = 0;
	static long seq = 1;

	public static void main(String[] args) {
		long p1 = 0;
		long p2 = 1;
		fibonnaci(p1, p2);
		System.out.println(count);
	}

	private static void fibonnaci(long p1, long p2) {
		if ((p1+p2) <= 4000000) {
			if ((p1+p2) % 2 == 0)
				count += (p1+p2);
			fibonnaci(p2, p1 + p2);
		} else
			return;
	}

}
